AWSTemplateFormatVersion: '2010-09-09'

Description: Smart Attendance and Leave Portal Infrastructure with EC2

Parameters:

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Resources:

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SmartAttendance-Users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

  AttendanceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SmartAttendance-Attendance
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: attendanceId
          AttributeType: S
      KeySchema:
        - AttributeName: attendanceId
          KeyType: HASH

  LeaveRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SmartAttendance-LeaveRequests
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: leaveId
          AttributeType: S
      KeySchema:
        - AttributeName: leaveId
          KeyType: HASH

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: smart-attendance-cloudformation-mansi

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SmartAttendance-CloudFormation-Lambda-Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Smart Attendance EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  AttendanceEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t3.micro
      Tags:
        - Key: Name
          Value: SmartAttendance-EC2

Outputs:

  UsersTableName:
    Value: !Ref UsersTable

  AttendanceTableName:
    Value: !Ref AttendanceTable

  LeaveRequestsTableName:
    Value: !Ref LeaveRequestsTable

  FrontendBucketName:
    Value: !Ref FrontendBucket

  LambdaRoleName:
    Value: !Ref LambdaExecutionRole

  EC2InstanceId:
    Value: !Ref AttendanceEC2

  EC2PublicIP:
    Value: !GetAtt AttendanceEC2.PublicIp
